// Package memory provides typed, validated metadata schemas for knowledge nodes.
// Context nodes are out of scope (they use jot.ContextMetadata in the main package).
package memory

import (
	"encoding/json"
	"errors"
	"fmt"
	"strings"
)

// Node type constants for use by callers and the registry.
const (
	NodeTypePerson         = "person"
	NodeTypeProject        = "project"
	NodeTypeGoal           = "goal"
	NodeTypePreference     = "preference"
	NodeTypeEvent          = "event"
	NodeTypeMilestone      = "milestone"
	NodeTypePlace          = "place"
	NodeTypeAsset          = "asset"
	NodeTypeTool           = "tool"
	NodeTypeGeneric        = "generic"
	NodeTypeWeeklySummary = "weekly_summary"
	// NodeTypeIdentity is the reserved identity-anchor node type. Janitor must not delete or archive these.
	NodeTypeIdentity = "identity_anchor"
	// NodeTypeUserIdentity is for self-referential statements about the user's core identity (name, role, values, traits). Janitor must not delete these.
	NodeTypeUserIdentity = "user_identity"
	// NodeTypeLog is for episodic log entries (raw ingest from all channels).
	NodeTypeLog = "log"
	// NodeTypeTask is for task/todo items managed by the task engine.
	NodeTypeTask = "task"
	// NodeTypeQuery is for logged queries (Q&A pairs) from the FOH loop.
	NodeTypeQuery = "query"
	// NodeTypePendingQuestion is for gap/contradiction questions to be clarified by the user.
	NodeTypePendingQuestion = "pending_question"
	// NodeTypeRelationship is a reified edge connecting two entity nodes.
	NodeTypeRelationship = "relationship"
	// NodeTypeObject is a generic graph object node extracted by the Loom refinery pipeline.
	NodeTypeObject = "object"
	// NodeTypeResponse is an async proactive response node generated by the Loom response worker.
	NodeTypeResponse = "response"
)

// AllowedPredicates is the canonical relationship ontology used by Refinery.
var AllowedPredicates = []string{
	"works_at",
	"prefers",
	"owns",
	"lives_in",
	"located_in",
	"collaborates_with",
	"reports_to",
	"manages",
}

var allowedPredicateSet = func() map[string]struct{} {
	out := make(map[string]struct{}, len(AllowedPredicates))
	for _, p := range AllowedPredicates {
		out[p] = struct{}{}
	}
	return out
}()

var predicateAliasMap = map[string]string{
	"work_at":            "works_at",
	"works_for":          "works_at",
	"employed_by":        "works_at",
	"moved_to":           "lives_in",
	"relocated_to":       "lives_in",
	"resides_in":         "lives_in",
	"live_in":            "lives_in",
	"lives_at":           "lives_in",
	"located_at":         "located_in",
	"based_in":           "located_in",
	"collaborates":       "collaborates_with",
	"collaboratesw_with": "collaborates_with",
	"manage":             "manages",
	"reports":            "reports_to",
}

// IsAllowedPredicate reports whether predicate is in the canonical ontology.
func IsAllowedPredicate(predicate string) bool {
	_, ok := allowedPredicateSet[CanonicalizePredicate(predicate)]
	return ok
}

// CanonicalizePredicate normalizes a raw predicate and maps known aliases into the
// canonical ontology. Unknown predicates are returned in normalized form to preserve
// potentially useful relations while still allowing callers to detect ontology gaps.
func CanonicalizePredicate(raw string) string {
	p := NormalizedPredicate(raw)
	if mapped, ok := predicateAliasMap[p]; ok {
		return mapped
	}
	return p
}

// SnapAllowedPredicate maps a raw predicate to the nearest canonical ontology entry.
// It first normalizes, then checks common aliases.
func SnapAllowedPredicate(raw string) (string, bool) {
	p := CanonicalizePredicate(raw)
	if _, ok := allowedPredicateSet[p]; ok {
		return p, true
	}
	return "", false
}

// CanonicalEntityNodeType normalizes extractor-provided entity types to known node types.
// Unknown or empty values fall back to person for backwards compatibility.
func CanonicalEntityNodeType(raw string) string {
	t := strings.TrimSpace(strings.ToLower(raw))
	switch t {
	case NodeTypePerson, "people", "human":
		return NodeTypePerson
	case NodeTypePlace, "location", "city", "country", "building", "venue", "hotel", "restaurant", "room":
		return NodeTypePlace
	case NodeTypeProject, "work":
		return NodeTypeProject
	case NodeTypeGoal:
		return NodeTypeGoal
	case NodeTypePreference:
		return NodeTypePreference
	case NodeTypeEvent, "meeting", "occasion", "celebration", "trip":
		return NodeTypeEvent
	case NodeTypeMilestone:
		return NodeTypeMilestone
	case NodeTypeAsset, "object", "item", "thing", "structure", "deck", "furniture":
		return NodeTypeAsset
	case NodeTypeTool:
		return NodeTypeTool
	case NodeTypeGeneric:
		return NodeTypeGeneric
	default:
		return NodeTypeGeneric
	}
}

const (
	userIdentityCategoryName  = "name"
	userIdentityCategoryRole  = "role"
	userIdentityCategoryValue = "value"
	userIdentityCategoryTrait = "trait"
)

// Project/Goal status values (metadataStatus and existing code expect lowercase).
const (
	StatusActive    = "active"
	StatusArchived  = "archived"
	StatusBlocked   = "blocked"
	StatusDone      = "done"
	StatusPlanning  = "planning"
	StatusPending   = "pending"
	StatusCompleted = "completed"
)

// Task status values — used by the task engine.
const (
	TaskStatusPending   = "pending"
	TaskStatusActive    = "active"
	TaskStatusCompleted = "completed"
	TaskStatusAbandoned = "abandoned"
)

const (
	categoryFood     = "food"
	categoryWorkflow = "workflow"
	categoryTech     = "tech"
	sentimentLike    = "like"
	sentimentDislike = "dislike"
	sentimentRigid   = "rigid"

	eventTypeCelebration = "celebration"
	eventTypeWork        = "work"
	eventTypeHealth      = "health"

	placeCategoryHome   = "home"
	placeCategoryOffice = "office"
	placeCategoryTravel = "travel"

	assetTypeSoftware = "software"
	assetTypeHardware = "hardware"
	assetTypeAccount  = "account"
)

// CanonicalMapConfig is the singleton config document stored at Firestore path
// `_config/canonical_map`. It holds the live predicate ontology and entity type list
// used by the Loom refinery pipeline. Falls back to AllowedPredicates if the doc
// doesn't exist yet (cold start).
type CanonicalMapConfig struct {
	AllowedPredicates []string `firestore:"allowed_predicates" json:"allowed_predicates"`
	EntityTypes       []string `firestore:"entity_types"       json:"entity_types"`
}

type validatorFunc func(map[string]any) error
type normalizerFunc func(map[string]any) (map[string]any, error)

var userIdentityCategories = map[string]bool{
	userIdentityCategoryName: true, userIdentityCategoryRole: true,
	userIdentityCategoryValue: true, userIdentityCategoryTrait: true,
}

func validateUserIdentity(m map[string]any) error {
	c := getString(m, "category")
	if c != "" && !userIdentityCategories[strings.ToLower(c)] {
		return fmt.Errorf("invalid category %q for user_identity (use name, role, value, trait or omit)", c)
	}
	return nil
}

func normalizeUserIdentity(m map[string]any) (map[string]any, error) {
	out := make(map[string]any)
	c := getString(m, "category")
	if c != "" {
		out["category"] = strings.ToLower(c)
	}
	return out, nil
}

var registry = map[string]struct {
	validate  validatorFunc
	normalize normalizerFunc
}{
	NodeTypePerson:       {validate: validatePerson, normalize: normalizePerson},
	NodeTypeProject:      {validate: validateProjectGoal, normalize: normalizeProjectGoal},
	NodeTypeGoal:         {validate: validateProjectGoal, normalize: normalizeProjectGoal},
	NodeTypePreference:   {validate: validatePreference, normalize: normalizePreference},
	NodeTypeEvent:        {validate: validateEventMilestone, normalize: normalizeEventMilestone},
	NodeTypeMilestone:    {validate: validateEventMilestone, normalize: normalizeEventMilestone},
	NodeTypePlace:        {validate: validatePlace, normalize: normalizePlace},
	NodeTypeAsset:        {validate: validateAssetTool, normalize: normalizeAssetTool},
	NodeTypeTool:         {validate: validateAssetTool, normalize: normalizeAssetTool},
	NodeTypeGeneric:      {validate: validateGeneric,   normalize: normalizeGeneric},
	NodeTypeObject:       {validate: validateObject,   normalize: normalizeObject},
	NodeTypeResponse:     {validate: validateResponse, normalize: normalizeResponse},
	NodeTypeUserIdentity: {validate: validateUserIdentity, normalize: normalizeUserIdentity},
}

// IsRegistered returns true if nodeType has a schema in the registry.
func IsRegistered(nodeType string) bool {
	_, ok := registry[nodeType]
	return ok
}

// ValidateMetadata validates m against the schema for nodeType.
// On schema violations it returns a *MemoryError with Code: CodeValidation,
// classifiable via IsValidationError. A nil map returns a plain error (programming error).
func ValidateMetadata(nodeType string, m map[string]any) error {
	if m == nil {
		return errors.New("metadata map is nil")
	}
	entry, ok := registry[nodeType]
	if !ok {
		return nil
	}
	if err := entry.validate(m); err != nil {
		return &MemoryError{
			Code:    CodeValidation,
			Message: fmt.Sprintf("invalid metadata for %q", nodeType),
			Err:     err,
		}
	}
	return nil
}

// NormalizeMetadata normalizes m for the given nodeType.
func NormalizeMetadata(nodeType string, m map[string]any) (map[string]any, error) {
	if m == nil {
		return map[string]any{}, nil
	}
	entry, ok := registry[nodeType]
	if !ok {
		return m, nil
	}
	return entry.normalize(m)
}

// MetadataToJSON marshals the normalized map to a JSON string for storage.
func MetadataToJSON(m map[string]any) (string, error) {
	if m == nil {
		return "{}", nil
	}
	b, err := json.Marshal(m)
	if err != nil {
		return "", fmt.Errorf("marshal metadata: %w", err)
	}
	return string(b), nil
}

func validatePerson(m map[string]any) error { return nil }

func normalizePerson(m map[string]any) (map[string]any, error) {
	out := make(map[string]any)
	setString(out, "relationship_strength", getString(m, "relationship_strength"))
	setString(out, "occupation", getString(m, "occupation"))
	setString(out, "birthdate", getString(m, "birthdate"))
	setString(out, "last_interaction", getString(m, "last_interaction"))
	setStringSlice(out, "interests", getStringSlice(m, "interests"))
	return out, nil
}

var projectGoalStatuses = map[string]bool{
	StatusActive: true, StatusArchived: true, StatusBlocked: true, StatusDone: true,
	StatusPlanning: true, StatusPending: true, StatusCompleted: true,
}

func validateProjectGoal(m map[string]any) error {
	s := getString(m, "status")
	if s != "" && !projectGoalStatuses[strings.ToLower(s)] {
		return fmt.Errorf("invalid status %q for project/goal", s)
	}
	return nil
}

func normalizeProjectGoal(m map[string]any) (map[string]any, error) {
	out := make(map[string]any)
	pid := getString(m, "parent_goal")
	if pid == "" {
		pid = getString(m, "parent_goal_id")
	}
	if pid == "" {
		pid = getString(m, "project_uuid")
	}
	if pid != "" {
		out["parent_goal"] = pid
		out["project_uuid"] = pid
	}
	s := getString(m, "status")
	if s != "" {
		out["status"] = strings.ToLower(s)
	}
	setString(out, "deadline", getString(m, "deadline"))
	setString(out, "archive_summary", getString(m, "archive_summary"))
	if v, ok := m["step_number"]; ok {
		out["step_number"] = v
	}
	if v, ok := m["dependencies"]; ok {
		out["dependencies"] = v
	}
	return out, nil
}

var preferenceCategories = map[string]bool{categoryFood: true, categoryWorkflow: true, categoryTech: true}
var preferenceSentiments = map[string]bool{sentimentLike: true, sentimentDislike: true, sentimentRigid: true}

func validatePreference(m map[string]any) error {
	c := getString(m, "category")
	if c != "" && !preferenceCategories[strings.ToLower(c)] {
		return fmt.Errorf("invalid category %q for preference", c)
	}
	s := getString(m, "sentiment")
	if s != "" && !preferenceSentiments[strings.ToLower(s)] {
		return fmt.Errorf("invalid sentiment %q for preference", s)
	}
	return nil
}

func normalizePreference(m map[string]any) (map[string]any, error) {
	out := make(map[string]any)
	setString(out, "subject", getString(m, "subject"))
	c := getString(m, "category")
	if c != "" {
		out["category"] = strings.ToLower(c)
	}
	s := getString(m, "sentiment")
	if s != "" {
		out["sentiment"] = strings.ToLower(s)
	}
	return out, nil
}

var eventTypes = map[string]bool{eventTypeCelebration: true, eventTypeWork: true, eventTypeHealth: true}

func validateEventMilestone(m map[string]any) error {
	t := getString(m, "type")
	if t != "" && !eventTypes[strings.ToLower(t)] {
		return fmt.Errorf("invalid type %q for event/milestone", t)
	}
	return nil
}

func normalizeEventMilestone(m map[string]any) (map[string]any, error) {
	out := make(map[string]any)
	setString(out, "date", getString(m, "date"))
	t := getString(m, "type")
	if t != "" {
		out["type"] = strings.ToLower(t)
	}
	setStringSlice(out, "attendees", getStringSlice(m, "attendees"))
	return out, nil
}

var placeCategories = map[string]bool{placeCategoryHome: true, placeCategoryOffice: true, placeCategoryTravel: true}

func validatePlace(m map[string]any) error {
	c := getString(m, "category")
	if c != "" && !placeCategories[strings.ToLower(c)] {
		return fmt.Errorf("invalid category %q for place", c)
	}
	return nil
}

func normalizePlace(m map[string]any) (map[string]any, error) {
	out := make(map[string]any)
	setString(out, "address", getString(m, "address"))
	c := getString(m, "category")
	if c != "" {
		out["category"] = strings.ToLower(c)
	}
	setString(out, "notes", getString(m, "notes"))
	return out, nil
}

var assetTypes = map[string]bool{assetTypeSoftware: true, assetTypeHardware: true, assetTypeAccount: true}

func validateAssetTool(m map[string]any) error {
	t := getString(m, "type")
	if t != "" && !assetTypes[strings.ToLower(t)] {
		return fmt.Errorf("invalid type %q for asset/tool", t)
	}
	return nil
}

func normalizeAssetTool(m map[string]any) (map[string]any, error) {
	out := make(map[string]any)
	t := getString(m, "type")
	if t != "" {
		out["type"] = strings.ToLower(t)
	}
	if v, ok := m["configuration"]; ok && v != nil {
		out["configuration"] = v
	}
	if v, ok := m["preferences"]; ok && v != nil {
		out["preferences"] = v
	}
	return out, nil
}

func validateObject(m map[string]any) error { return nil }

func normalizeObject(m map[string]any) (map[string]any, error) {
	out := make(map[string]any)
	setString(out, "source_excerpt", getString(m, "source_excerpt"))
	setStringSlice(out, "tags", getStringSlice(m, "tags"))
	return out, nil
}

func validateResponse(m map[string]any) error { return nil }

func normalizeResponse(m map[string]any) (map[string]any, error) {
	out := make(map[string]any)
	setString(out, "logic_trace", getString(m, "logic_trace"))
	setString(out, "source_entry_uuid", getString(m, "source_entry_uuid"))
	return out, nil
}

func validateGeneric(m map[string]any) error { return nil }

func normalizeGeneric(m map[string]any) (map[string]any, error) {
	out := make(map[string]any)
	setString(out, "source_excerpt", getString(m, "source_excerpt"))
	setStringSlice(out, "extracted_facts", getStringSlice(m, "extracted_facts"))
	if v, ok := m["confidence_score"]; ok {
		switch x := v.(type) {
		case float64:
			out["confidence_score"] = x
		case int:
			out["confidence_score"] = float64(x)
		default:
			out["confidence_score"] = 0.0
		}
	} else {
		out["confidence_score"] = 0.0
	}
	setStringSlice(out, "tags", getStringSlice(m, "tags"))
	return out, nil
}

func getString(m map[string]any, key string) string {
	v, ok := m[key]
	if !ok {
		return ""
	}
	s, _ := v.(string)
	return s
}

func setString(m map[string]any, key, value string) {
	if value != "" {
		m[key] = value
	}
}

func getStringSlice(m map[string]any, key string) []string {
	v, ok := m[key]
	if !ok {
		return nil
	}
	switch x := v.(type) {
	case []string:
		return x
	case []any:
		out := make([]string, 0, len(x))
		for _, e := range x {
			if s, ok := e.(string); ok {
				out = append(out, s)
			}
		}
		return out
	default:
		return nil
	}
}

func setStringSlice(m map[string]any, key string, s []string) {
	if len(s) > 0 {
		m[key] = s
	}
}

// SPOTriple holds a parsed Subject | Predicate | Object triple.
type SPOTriple struct {
	Subject   string
	Predicate string
	Object    string
}

// ParseSPOTriple parses a fact line that may be in "Subject | Predicate | Object" format.
// Returns a non-nil *SPOTriple only when the line contains exactly two "|" separators.
// Returns nil when the line is a flat-format fact (e.g. "[WIFE] Gloria: ...").
func ParseSPOTriple(line string) *SPOTriple {
	parts := strings.SplitN(line, "|", 3)
	if len(parts) != 3 {
		return nil
	}
	s := strings.TrimSpace(parts[0])
	p := strings.TrimSpace(parts[1])
	o := strings.TrimSpace(parts[2])
	if s == "" || p == "" || o == "" {
		return nil
	}
	return &SPOTriple{Subject: s, Predicate: p, Object: o}
}

// IsSPOTriple returns true if the fact line is in Subject | Predicate | Object format.
func IsSPOTriple(line string) bool {
	return ParseSPOTriple(line) != nil
}

// NormalizedPredicate lowercases and replaces spaces/hyphens with underscores so predicates
// are stored consistently (e.g. "works at" → "works_at").
func NormalizedPredicate(raw string) string {
	r := strings.ToLower(strings.TrimSpace(raw))
	r = strings.ReplaceAll(r, " ", "_")
	r = strings.ReplaceAll(r, "-", "_")
	return r
}
